### ISSUE TITLE
Installation of devkitA64 along existing old version of devkitPPC interfere with it

### ISSUE THREAD

**Issue by iyenal** [devkitPro/installer#14]
Installed recently devkitA64 as I have to compile some switch projects, along devkitPPC which is installed since a while ago, using an old release as I use libs which don't links to correct references in newer ones. But after I installed that devkitA64 with this installer, it changed something also in devkitPPC and the error which originally come from new devkitPPC re-appeared (" undefined reference to `__ctype_ptr__' " which I fixed previously using r27).

Not only the original SourceForge repo got wiped so I can't downgrade installing manually old versions, but the biggest problem is that the installer shouldn't touch to anything else than devkitA64 if I only ask to install devkitA64.

Without being negative, looks like this "automated installer" brings more hassle than it should...

**Comment by iyenal** [comment]
So yeah, in addition I think the installer should let the choice to install old versions as we don't always have time to re-compile and re-update all the missing dependencies in newer ones. Or at least an archive repo with all the binairies since the first release, if that's not an another one I am not aware about. (don't mean to be negative there, I am very grateful for what DevkitPro provides us for free today, I just think that a lot of things could be improved very easily ;))

**Comment by WinterMute** [comment]
We don't support old releases - many bugs have been fixed, standards complied with and improvements made since the first release. Providing old binaries creates obligations we can't fulfil and using old binaries risks running into bugs that have long been fixed.

We do supply various pre-compiled libraries which are updated for new toolchains and library updates as required. If there's something missing then please submit a PR for a package or request that one be created.

https://github.com/devkitPro/pacman-packages

**Comment by iyenal** [comment]
"Providing old binaries creates obligations" -I am not sure about that. You can provide old binairies without providing support for them, it is our problem that we want to use it. And even for archive purposes.

"risks running into bugs that have long been fixed" -again, that's our problem, not yours as it is understandable you don't want to waste time supporting obsolete releases.

So yeah I don't see how it is problematic to have a releases archive.
