### ISSUE TITLE
libwinpthread-1.dll not found issue

### ISSUE THREAD

**Issue by JLaferri** [devkitPro/installer#16]
I was trying to build the latest version of Nintendont using a fresh GBA, GC, and Wii toolchain install. Hence I had the latest `devkitARM` `devkitPPC` and `libogc`. When trying to build it I would encounter an error that looked like:
```
make -C multidol
make[1]: Entering directory '/home/Jas/Documents/GitHub/Nintendont/multidol'
 ASSEMBLE    crt0.S
make[1]: *** [Makefile:36: crt0.o] Error 1
make[1]: Leaving directory '/home/Jas/Documents/GitHub/Nintendont/multidol'
make: *** [Makefile:34: multidol] Error 2
```
Upon further inspection, I was able to track the error down to:
![image](https://user-images.githubusercontent.com/1534726/53046679-9bfb0400-345e-11e9-8fe3-bb97aa16c28d.png)

I fixed the issue by copying `libwinpthread-1.dll` from `devkitPPC/bin` to `devkitPPC/libexec/gcc/powerpc-eabi/8.2.0`. I then did the same with `devkitARM`.

Should the windows installer have added something to my path that it left out? Or should this dll exist where I copied it to? Or was there just something wrong with my system?

**Comment by WinterMute** [comment]
Please don't copy dlls around. This is an issue with Nintendont. The tools should not be called by full path but rather simply by name with /opt/devkitpro/devkitPPC/bin in PATH. This path should not be added to path permanently due to the potential for collision with powerpc-eabi cross tools for different platforms.

Ideally user projects should include at least /opt/devkitpro/devkitPPC/base_tools - see https://github.com/devkitPro/devkitppc-rules/blob/master/base_tools
