### ISSUE TITLE
Windows 10 32-bit Installation?

### ISSUE THREAD

**Issue by creativegamer03** [devkitPro/installer#32]
How do I install it for Windows 10 32-bit, since the installer shows a pop-up error window saying "Sorry, this installer only supports 64 bit" ?

**Comment by thejsa** [comment]
32-bit Windows isn't really supported anymore, as I understand it, due to a lack of 32-bit support in msys2 which dkP toolchains rely on to provide Unix-y tools; see #18, #23 where people have asked about this before.

You might be able to get it working by using an older build of msys2 which still has 32-bit support (the last being in July 2020) and manually configuring it using the instructions at https://devkitpro.org/wiki/devkitPro_pacman#Customising_Existing_Pacman_Install -- but I would really strongly recommend upgrading to Windows 10 64-bit if at all possible.

**Comment by pinobatch** [comment]
Reporter's PC is a detachable tablet PC with 1 GB RAM, presumably soldered-in. This meets the [minimum requirements](https://support.microsoft.com/en-us/windows/windows-10-system-requirements-6d4e9a79-66bf-7950-467c-795cf0386715) for Windows 10 32-bit but not Windows 10 64-bit.

**Comment by thejsa** [comment]
> Reporter's PC is a detachable tablet PC with 1 GB RAM, presumably soldered-in. This meets the [minimum requirements](https://support.microsoft.com/en-us/windows/windows-10-system-requirements-6d4e9a79-66bf-7950-467c-795cf0386715) for Windows 10 32-bit but not Windows 10 64-bit.

In this case the workaround mentioned *should* get things working, but OP is not in for a great time over the next few years as more and more things drop 32-bit support, so worth looking into getting an alternative machine if they can (would say Linux, but drivers can be iffy on those tablets from experience)

**Comment by WinterMute** [comment]
The instructions at https://devkitpro.org/wiki/devkitPro_pacman link to the 32bit msys2 installer and have instructions for adding the tools manually. Unfortunately it's growing increasingly difficult to support 32bit machines and I'm really not sure just how much longer we can keep this up.
