### ISSUE TITLE
32bit installer

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [devkitPro/installer#40]
where it is? and why there is a 64bit installer when nothing here should require 64bit?

**Comment by AerGlass** [comment]
almost all unix tools don't support 32 bit anymore, including msys.

**Comment by MyTDT-Mysoft** [comment]
it may make sense for linux... but for windows where everything runs 32bit without needing extra... it totally does not so its sad that then :p but i would rather use an old msys than accept this bullshit

https://wii.leseratte10.de/devkitPro/

i'm really on stuff from this guy to have the 32bit executables while the rest i can grab from official...
but its very bad when devkitpro not only work but stopped archiving releases and forcing the usage of a installer that does not work :P

**Comment by AerGlass** [comment]
You can still download 32 bit msys though.

**Comment by WinterMute** [comment]
The installer is set to 64bit because msys2 only supports 64bit now. Microsoft are also in the process of removing support for 32bit windows.

If you're really, really stuck on 32bit then you can use the last msys2 32bit installer from https://repo.msys2.org/distrib/msys2-i686-latest.exe then use the manual instructions found at https://devkitpro.org/wiki/devkitPro_pacman#Customising_Existing_Pacman_Install to add the devkitPro repositories.

There are plans to replace this installer but we haven't yet got around to it. We may include 32bit support then, it depends on how much demand there is really.
